# Generated by Django 3.2.5 on 2024-03-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0003_auto_20240306_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Rent', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
    ]
