# Generated by Django 3.2.5 on 2024-03-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0006_auto_20240306_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Second Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Third Image'),
        ),
    ]
